services:
  db:
    env_file: .env
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: solaceassignment
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  psql:
    name: solaceassignment
